
Vagrant.configure(2) do |config|
  config.vm.box = "parallels/ubuntu-14.04"

  config.vm.network "forwarded_port", guest: 80, host: 8080 # web
  config.vm.network "forwarded_port", guest: 81, host: 8081 # phpmyadmin
  config.vm.network "forwarded_port", guest: 8025, host: 8082 # mailhog

  config.vm.provision "shell", path: "../install_lamp.sh"
end